#!/usr/bin/env python
# Copyright (c) 2013-Present, Scott Cagno
# All rights reserved. [BSD License]

# imports
from __init__ import typ, key, bsh, snp

live = True
togg = "TOGGLE-BASE"
name = "BASE-SCOPE"
kind = "BASE"
cmds = {	

	"ALPHA"				:	[ typ("a") ],
	"BRAVO"				:	[ typ("b") ],
	"CHARLIE"			:	[ typ("c") ],
	"DELTA"				:	[ typ("d") ], 
	"ECHO"				:	[ typ("e") ],
	"FOXTROT"			:	[ typ("f") ],
	"GOLF"				:	[ typ("g") ],
	"HOTEL"				:	[ typ("h") ],
	"INDIA"				:	[ typ("i") ],
	"JULIE"				:	[ typ("j") ],
	"KILO"				:	[ typ("k") ],
	"LIMA"				:	[ typ("l") ],
	"MIKE"				:	[ typ("m") ],
	"NOVEMBER"			:	[ typ("n") ],
	"OSCAR"				:	[ typ("o") ],
	"PAPA"				:	[ typ("p") ],
	"QUEBEC"			:	[ typ("q") ],
	"ROMEO"				:	[ typ("r") ],
	"SIERRA"			:	[ typ("s") ],
	"TANGO"				:	[ typ("t") ],
	"UNIFORM"			:	[ typ("u") ],
	"VICTOR"			:	[ typ("v") ],
	"WHISKEY"			:	[ typ("w") ],
	"X-RAY"				:	[ typ("x") ],
	"YANKEE"			:	[ typ("y") ],
	"ZEN"				:	[ typ("z") ],

	"CAP-ALPHA"			:	[ typ("A") ],
	"CAP-BRAVO"			:	[ typ("B") ],
	"CAP-CHARLIE"		:	[ typ("C") ],
	"CAP-DELTA"			:	[ typ("D") ], 
	"CAP-ECHO"			:	[ typ("E") ],
	"CAP-FOXTROT"		:	[ typ("F") ],
	"CAP-GOLF"			:	[ typ("G") ],
	"CAP-HOTEL"			:	[ typ("H") ],
	"CAP-INDIA"			:	[ typ("I") ],
	"CAP-JULIE"			:	[ typ("J") ],
	"CAP-KILO"			:	[ typ("K") ],
	"CAP-LIMA"			:	[ typ("L") ],
	"CAP-MIKE"			:	[ typ("M") ],
	"CAP-NOVEMBER"		:	[ typ("N") ],
	"CAP-OSCAR"			:	[ typ("O") ],
	"CAP-PAPA"			:	[ typ("P") ],
	"CAP-QUEBEC"		:	[ typ("Q") ],
	"CAP-ROMEO"			:	[ typ("R") ],
	"CAP-SIERRA"		:	[ typ("S") ],
	"CAP-TANGO"			:	[ typ("T") ],
	"CAP-UNIFORM"		:	[ typ("U") ],
	"CAP-VICTOR"		:	[ typ("V") ],
	"CAP-WHISKEY"		:	[ typ("W") ],
	"CAP-X-RAY"			:	[ typ("X") ],
	"CAP-YANKEE"		:	[ typ("Y") ],
	"CAP-ZEN"			:	[ typ("Z") ],

	"PERIOD"			:	[ typ(".") ],
	"SPACE"				:	[ typ(" ") ],
	"COMMA"				:	[ typ(",") ],
	"COLON"				:	[ typ(":") ],
	"SEMI-COLIN"		:	[ typ(";") ],
	"EXCLAMATION-POINT"	:	[ typ("!") ],
	"QUESTION-MARK"		:	[ typ("?") ],
	"AT"				:	[ typ("@") ],
	"DOLLAR"			:	[ typ("$") ],
	"PERCENT"			:	[ typ("%") ],
	"POUND"				:	[ typ("#") ],
	"SLASH"				:	[ typ("/") ],
	"UNDERSCORE"		:	[ typ("_") ],
	"APPOSTROPY"		:	[ typ("'") ],

	"ZERO"				:	[ typ("0") 		],
	"ONE"				:	[ typ("1") 		],
	"TWO"				:	[ typ("2") 		],
	"THREE"				:	[ typ("3") 		],
	"FOUR"				:	[ typ("4") 		],
	"FIVE"				:	[ typ("5") 		],
	"SIX"				:	[ typ("6") 		],
	"SEVEN"				:	[ typ("7") 		],
	"EIGHT"				:	[ typ("8") 		],
	"NINE"				:	[ typ("9") 		],
	"HUNDRED"			:	[ typ("00") 	],
	"THOUSAND"			:	[ typ("000") 	],
	"MILLOIN"			:	[ typ("000000") ],

	"TAB"				:	[ key("Tab") 		],
	"NEXT"				:	[ key("Tab") 		],
	"ALLCAPS"			:	[ key("Caps_Lock") 	],
	"SLAP"				:	[ key("Return") 	],
	"ENTER"				:	[ key("Return") 	],
	"DELETE"			:	[ key("Delete") 	],
	"DEL"				:	[ key("Delete") 	],

	"MODULUS"			:	[ typ("%") 									],
	"TIMES"				:	[ typ("*") 									],
	"DIVIDE"			:	[ typ("/") 									],
	"MINUS"				:	[ typ("-") 									],
	"PLUS"				:	[ typ("+") 									],
	"EQUALS"			:	[ typ("=") 									],
	"POW"				:	[ typ("**") 								],
	"EXPONENT"			:	[ typ("**") 								],
	"PIE"				:	[ typ("3.14") 								],
	"FIBINACHI"			:	[ typ("0,1,1,2,3,5,8,13,21,34,55,89,144") 	],
	"BITSHIFT"			:	[ typ(" << ") 								],
	"BITWISE"			:	[ typ(" << ") 								],

	"PAREN"				:	[ typ("()"), key("Left") 	],
	"BRACKET"			:	[ typ("[]"), key("Left") 	],
	"BRACE"				:	[ typ("{}"), key("Left") 	],
	"QUOTE"				:	[ typ("\"\""), key("Left") 	],
	"SINGLE-QUOTE"		:	[ typ("''"), key("Left") 	],
	"ELIPSIS"			:	[ typ("...") 				],

	"UNIXNANO-STAMP"	:	[ bsh("date +%s%N") ],
	"UNIXNANO-E-POCK"	:	[ bsh("date +%s%N") ],
	"UNIX-STAMP"		:	[ bsh("date +%s") 	],
	"UNIX-E-POCK"		:	[ bsh("date +%s") 	],
	"TIME-STAMP"		:	[ bsh("date +%T") 	],
	"DATE-STAMP"		:	[ bsh("date +%D") 	],

	"ADD-VOCAB"			:	[ typ("add_vocab"), key("Return") ]
}